export const languagesList = {
  en: {
    start: "Get Started",
    signIn: "Sign In",
    signUp: "Sign Up",
    name: "Enter Your Name",
    mail: "Enter Your Email Address",
    Password: "Enter Your Password",
    searchInBrowse: "Search Movies using AI!",
    logOut: "Logout",
    play: "Play",
    info: "Movie Info",
    home: "Back to Home",
    placeHolder: "What movies would you like to watch?",
    searchMovies: "Search",
  },
  hi: {
    start: "शुरू करें",
    signIn: "साइन इन करें",
    signUp: "साइन अप करें",
    name: "अपना नाम दर्ज करें",
    mail: "अपना ईमेल पता दर्ज करें",
    Password: "अपना पासवर्ड दर्ज करें",
    searchInBrowse: "AI का उपयोग करके फिल्में खोजें!",
    logOut: "लॉग आउट",
    play: "चलाएं",
    info: "फिल्म की जानकारी",
    home: "मुखपृष्ठ पर वापस जाएं",
    searchMovies: "खोजें",
    placeHolder: "आप कौन सी फिल्में देखना चाहेंगे?",
  },
  de: {
    start: "Loslegen",
    signIn: "Anmelden",
    signUp: "Registrieren",
    name: "Geben Sie Ihren Namen ein",
    mail: "Geben Sie Ihre E-Mail-Adresse ein",
    Password: "Geben Sie Ihr Passwort ein",
    searchInBrowse: "Filme mit KI suchen!",
    logOut: "Abmelden",
    play: "Abspielen",
    info: "Filminformationen",
    home: "Zurück zur Startseite",
    searchMovies: "Suchen",
    placeHolder: "Welche Filme möchten Sie ansehen?",
  },
  es: {
    start: "Comenzar",
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    name: "Ingresa tu nombre",
    mail: "Ingresa tu correo electrónico",
    Password: "Ingresa tu contraseña",
    searchInBrowse: "¡Busca películas usando IA!",
    logOut: "Cerrar sesión",
    play: "Reproducir",
    info: "Información de la película",
    home: "Volver al inicio",
    searchMovies: "Buscar",
    placeHolder: "¿Qué películas te gustaría ver?",
  },
  ta: {
    start: "தொடங்கு",
    signIn: "உள்நுழைக",
    signUp: "பதிவுசெய்யவும்",
    name: "உங்கள் பெயரை உள்ளிடவும்",
    mail: "உங்கள் மின்னஞ்சல் முகவரியை உள்ளிடவும்",
    Password: "உங்கள் கடவுச்சொல்லை உள்ளிடவும்",
    searchInBrowse: "ஏஐ-ஐ பயன்படுத்தி திரைப்படங்களை தேடுங்கள்!",
    logOut: "வெளியேறு",
    play: "வாசிக்க",
    info: "திரைப்பட தகவல்",
    home: "முகப்புக்கு திரும்பு",
    searchMovies: "தேடல்",
    placeHolder: "நீங்கள் எந்த திரைப்படங்களை பார்க்க விரும்புகிறீர்கள்?",
  },
};
